language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit
  - sh -c "if [ '$TRAVIS_PHP_VERSION' != '7.0' ]; then vendor/bin/phpcs --report=full --extensions=php -pn --standard=build/phpcs .; fi"

matrix:
  allow_failures:
    - php: 5.3
    - php: 5.4
  fast_finish: true


notifications:
    on_success: never
    on_failure: always